name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*' # 触发条件：当推送带有 v 前缀的标签时，如 v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          echo "pnpm version: $(pnpm --version)"

      - name: Install dependencies
        run: pnpm install

      - name: Generate changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build extension packages
        run: pnpm run pack

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md # 使用 changelogithub 生成的变更日志
          draft: false
          prerelease: false

      - name: Upload extension.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension.zip
          asset_name: extension.zip
          asset_content_type: application/zip

      - name: Upload extension.crx
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension.crx
          asset_name: extension.crx
          asset_content_type: application/x-chrome-extension

      - name: Upload extension.xpi
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension.xpi
          asset_name: extension.xpi
          asset_content_type: application/x-xpinstall
